import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Logout } from "@/lib/action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/login">Login</Link>
          </li>
          <li>
            <Link href="/register">Register</Link>
          </li>
          <li>
            <Link href="/dashboard">Dashboard</Link>
          </li>
          <li>
            <form action={Logout}>
              <button type="submit">Logout</button>
            </form>
          </li>
        </ul>
        <div>{children}</div>
      </body>
    </html>
  );
}
